# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Principal
    url: '#about'
    weight: 10
  - name: Posts
    url: '#posts'
    weight: 20
  - name: Projectos
    url: '#projects'
    weight: 30
  - name: Publicaciones
    url: '#featured'
    weight: 50
  - name: Contacto
    url: '#contact'
    weight: 60
  - name: CV
    url: uploads/CV.pdf
    weight: 70
